### PR TITLE
kp frontpage fresh layout for review

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR will update KP Frontpage with new and fresh frontend.
To test:
1. Uninstall current KP Frontpage from your Tripal site instance. This will ensure that unused files/configuration/relations from the old layout will be deleted.
2. Update KP Frontpage and enable module from modules panel. At this stage the new module will create fields required in News and Events sections as well as initialize materialized view for a quick summary count of data under data section.
3. Congratulations! you now replaced the old KP with this new layout. You might want to add entries to news and events section.

NOTE: 
- Data count for genotype calls takes forever to generate, I added a limit in the query to only count the first 10 records. @laceysanderson you might have a swift method.
- The real-life image of each crops are result of google. I will do some follow up on our breeders to send us couple of pictures. So far I already have picture of Lentil (from Derek), Chickpea (from Bunyamin), Faba (from Lacey). Awaiting pictures of Dry Bean (from Kirstin) and Pea (from Tom).

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
I started off by just reviewing usage (not code). Here is my feedback:

## General
 - When I click on the KP logo it will go to `node/1` and all the images will break
 - Search tooltip is misleading. It should imply I can search all of KnowPulse not just germplasm and experiments.

## Top Quick Links Bar
- The following wording should be changed:
      - "Sign in KP" => "Sign in"
      - "Signup and Account" => "Create an Account"
 - Remove the "Request Password" link as this doesn't currently work...
 - "Add News * Events" should point directly to `node/add/kp-frontpage-cms`
 - Add a new link to "Add Biological Content" to `bio_data/add`
 - I would prefer this to be a solid navy, the diagonal lines are distracting to me.

## Hamburger Menu
- Perfect 👍 

## Crops
 - I Love everything about this section!!!

## Tools
 - Top tools should be: BLAST, JBrowse, Genotype Matrix, CVITjs, VCF Bulk Export, Experiments
 - Tools should not include searches (i.e.. markers, variants, sequences)
 - Change "Bulk Loader" to "VCF Bulk Export"
 - The grid looks weird to me when additional tools are expanded. I think you should either add margin between the rows or remove it within the rows between items.

## Data
 - Links within boxes need to show hierarchy. For example, Phenotypes needs to show that some links are for raw data and others for analyzed.
 - Counts didn't show up right away -the mview should be sync'd in the update/install hook
 - Check that all links will go to the new search pages (some urls have changed)
 - We will hopefully be adding Genetic Maps before this new frontpage launches. This creates a new data box.

## News & Events
 - Events showed up perfectly :-) 
 - I don't always want to provide a link... this field should be optional
 - when I added news it didn't display correctly: 
Screen Shot 2019-09-06 at 2 56 13 PM

**Review by laceysanderson — CHANGES_REQUESTED** [review]
## General
 - The following wording should be changed:
     - "Sign in KP" => "Sign in"
     - "Signup and Account" => "Create an Account"
 - "Add News * Events" should point directly to http://localhost/KnowPulse-TEST/node/add/kp-frontpage-cms. Updated points to `http://localhost/KnowPulse-TEST/admin/content/bio_data/add/kp-frontpage-cms`

## Tools
 - The grid looks weird to me when additional tools are expanded. I think you should either add margin between the rows or remove it within the rows between items.

## Data
 - Hierarchy looks to be hard-coded? it's fixed for phenotypic data now but not germplasm and genomic data.
- We can't just truncate the genotype calls like that. Check out https://wiki.postgresql.org/wiki/Count_estimate for a possibly faster way.

**Comment by reynoldtan** [comment]
News and Update issue - I just came up with a different name for the view so it does not conflict with the existing news and updates view. Simply reinstall the module and news and updates should work.

**Comment by reynoldtan** [comment]
quick-access-bar

Updates to Quick Access area while site-wide search functionality in development.

**Review by laceysanderson — APPROVED** [review]
Beautiful!!! 🎉

**Pull request merged**
